apiVersion: apps/v1
kind: Deployment
metadata:
  name: html-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: html-app
  template:
    metadata:
      labels:
        app: html-app
    spec:
      imagePullSecrets:
      - name: dockerhub-creds
      containers:
      - name: html-app
        imagePullPolicy: Always
        image: huytm1996/html-app:latest
        ports:
        - containerPort: 80

      - name: html-app2
        imagePullPolicy: Always
        image: huytm1996/html-app:latest
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: html-service
spec:
  selector:
    app: html-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31334
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: html-service2
spec:
  selector:
    app: html-app
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 31335
  type: NodePort
