apiVersion: apps/v1
kind: Deployment
metadata:
  name: html-app2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: html-app2
  template:
    metadata:
      labels:
        app: html-app2
    spec:
      imagePullSecrets:
      - name: dockerhub-creds
      containers:
      - name: html-app2
        image: huytm1996/html-app2:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: html2-service
spec:
  selector:
    app: html-app2
  ports:
  - port: 8081
    targetPort: 8081
    nodePort: 31335
  type: NodePort


